name: reddit-backend-dev
services:
  reddit-backend-dev:
    image: "maven:3-amazoncorretto-17-alpine"
    entrypoint: ["mvn", "spring-boot:run"]
    networks:
      - reddit-net
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/usr/src/reddit
      - .m2:/root/.m2
    working_dir: /usr/src/reddit
  mysql:
    image: "mysql:9"
    networks:
      - reddit-net
    environment:
      MYSQL_DATABASE: reddit
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: "redis:8.0-M02-alpine3.20"
    networks:
      - reddit-net
    volumes:
      - ./redis.conf:/usr/local/etc/redis
      - redis-data:/data

networks:
  reddit-net:

volumes:
  mysql-data:
  redis-data:

