spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  application:
    name: reddit-backend
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/reddit'
    username: 'root'
    password: ''
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
logging:
  level:
    me.project: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
junjiezh:
  app:
    jwtSecret: 86c2b0a44ec2116a0e822584c7bad3e1357b6417bb81c7957c8e9301b580049c
    jwtExpirationMs: 900000 # 15min
    jwtRefreshExpirationMs: 604800000 # 7d