spring:
  application:
    name: reddit-backend
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/reddit'
    username: 'root'
    password: ''
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always